---
title: FEETPIX NFT
author: ''
email: tentickles@feetpix.biz
description: 'FEETPIX NFT '
baseurl: "/ubuild-jekyll"
url: feetpix.biz
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
